#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="otomasyon")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertkullanıcı(kullanıcı instance);
    partial void Updatekullanıcı(kullanıcı instance);
    partial void Deletekullanıcı(kullanıcı instance);
    partial void Insertpersonel(personel instance);
    partial void Updatepersonel(personel instance);
    partial void Deletepersonel(personel instance);
    partial void Insertürünler(ürünler instance);
    partial void Updateürünler(ürünler instance);
    partial void Deleteürünler(ürünler instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::proje.Properties.Settings.Default.otomasyonConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<firmalar> firmalars
		{
			get
			{
				return this.GetTable<firmalar>();
			}
		}
		
		public System.Data.Linq.Table<kullanıcı> kullanıcıs
		{
			get
			{
				return this.GetTable<kullanıcı>();
			}
		}
		
		public System.Data.Linq.Table<personel> personels
		{
			get
			{
				return this.GetTable<personel>();
			}
		}
		
		public System.Data.Linq.Table<Sipari> Siparis
		{
			get
			{
				return this.GetTable<Sipari>();
			}
		}
		
		public System.Data.Linq.Table<ürünler> ürünlers
		{
			get
			{
				return this.GetTable<ürünler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.firmalar")]
	public partial class firmalar
	{
		
		private System.Nullable<int> _firmaid;
		
		private string _firma_adi;
		
		private string _adres;
		
		private System.Nullable<decimal> _telefon;
		
		private System.Nullable<int> _ürün_serino;
		
		public firmalar()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firmaid", DbType="Int")]
		public System.Nullable<int> firmaid
		{
			get
			{
				return this._firmaid;
			}
			set
			{
				if ((this._firmaid != value))
				{
					this._firmaid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firma_adi", DbType="NVarChar(50)")]
		public string firma_adi
		{
			get
			{
				return this._firma_adi;
			}
			set
			{
				if ((this._firma_adi != value))
				{
					this._firma_adi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="NVarChar(50)")]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this._adres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this._telefon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ürün_serino", DbType="Int")]
		public System.Nullable<int> ürün_serino
		{
			get
			{
				return this._ürün_serino;
			}
			set
			{
				if ((this._ürün_serino != value))
				{
					this._ürün_serino = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kullanıcı")]
	public partial class kullanıcı : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kullanıcıid;
		
		private string _kullanıcı_adi;
		
		private string _kullanıcı_sifre;
		
		private System.Nullable<decimal> _telefon;
		
		private string _mail;
		
		private string _kullanıcı_isim;
		
		private string _kullanıcı_soyisim;
		
		private EntitySet<ürünler> _ürünlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkullanıcıidChanging(int value);
    partial void OnkullanıcıidChanged();
    partial void Onkullanıcı_adiChanging(string value);
    partial void Onkullanıcı_adiChanged();
    partial void Onkullanıcı_sifreChanging(string value);
    partial void Onkullanıcı_sifreChanged();
    partial void OntelefonChanging(System.Nullable<decimal> value);
    partial void OntelefonChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    partial void Onkullanıcı_isimChanging(string value);
    partial void Onkullanıcı_isimChanged();
    partial void Onkullanıcı_soyisimChanging(string value);
    partial void Onkullanıcı_soyisimChanged();
    #endregion
		
		public kullanıcı()
		{
			this._ürünlers = new EntitySet<ürünler>(new Action<ürünler>(this.attach_ürünlers), new Action<ürünler>(this.detach_ürünlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanıcıid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kullanıcıid
		{
			get
			{
				return this._kullanıcıid;
			}
			set
			{
				if ((this._kullanıcıid != value))
				{
					this.OnkullanıcıidChanging(value);
					this.SendPropertyChanging();
					this._kullanıcıid = value;
					this.SendPropertyChanged("kullanıcıid");
					this.OnkullanıcıidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanıcı_adi", DbType="NVarChar(50)")]
		public string kullanıcı_adi
		{
			get
			{
				return this._kullanıcı_adi;
			}
			set
			{
				if ((this._kullanıcı_adi != value))
				{
					this.Onkullanıcı_adiChanging(value);
					this.SendPropertyChanging();
					this._kullanıcı_adi = value;
					this.SendPropertyChanged("kullanıcı_adi");
					this.Onkullanıcı_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanıcı_sifre", DbType="NVarChar(50)")]
		public string kullanıcı_sifre
		{
			get
			{
				return this._kullanıcı_sifre;
			}
			set
			{
				if ((this._kullanıcı_sifre != value))
				{
					this.Onkullanıcı_sifreChanging(value);
					this.SendPropertyChanging();
					this._kullanıcı_sifre = value;
					this.SendPropertyChanged("kullanıcı_sifre");
					this.Onkullanıcı_sifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="NVarChar(50)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanıcı_isim", DbType="NVarChar(50)")]
		public string kullanıcı_isim
		{
			get
			{
				return this._kullanıcı_isim;
			}
			set
			{
				if ((this._kullanıcı_isim != value))
				{
					this.Onkullanıcı_isimChanging(value);
					this.SendPropertyChanging();
					this._kullanıcı_isim = value;
					this.SendPropertyChanged("kullanıcı_isim");
					this.Onkullanıcı_isimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanıcı_soyisim", DbType="NVarChar(50)")]
		public string kullanıcı_soyisim
		{
			get
			{
				return this._kullanıcı_soyisim;
			}
			set
			{
				if ((this._kullanıcı_soyisim != value))
				{
					this.Onkullanıcı_soyisimChanging(value);
					this.SendPropertyChanging();
					this._kullanıcı_soyisim = value;
					this.SendPropertyChanged("kullanıcı_soyisim");
					this.Onkullanıcı_soyisimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kullanıcı_ürünler", Storage="_ürünlers", ThisKey="kullanıcıid", OtherKey="ürünid")]
		public EntitySet<ürünler> ürünlers
		{
			get
			{
				return this._ürünlers;
			}
			set
			{
				this._ürünlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ürünlers(ürünler entity)
		{
			this.SendPropertyChanging();
			entity.kullanıcı = this;
		}
		
		private void detach_ürünlers(ürünler entity)
		{
			this.SendPropertyChanging();
			entity.kullanıcı = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.personel")]
	public partial class personel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _personelid;
		
		private string _personel_adi;
		
		private string _personel_sifre;
		
		private int _personel_no;
		
		private System.Nullable<decimal> _telefon;
		
		private EntitySet<ürünler> _ürünlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpersonelidChanging(System.Nullable<int> value);
    partial void OnpersonelidChanged();
    partial void Onpersonel_adiChanging(string value);
    partial void Onpersonel_adiChanged();
    partial void Onpersonel_sifreChanging(string value);
    partial void Onpersonel_sifreChanged();
    partial void Onpersonel_noChanging(int value);
    partial void Onpersonel_noChanged();
    partial void OntelefonChanging(System.Nullable<decimal> value);
    partial void OntelefonChanged();
    #endregion
		
		public personel()
		{
			this._ürünlers = new EntitySet<ürünler>(new Action<ürünler>(this.attach_ürünlers), new Action<ürünler>(this.detach_ürünlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personelid", DbType="Int")]
		public System.Nullable<int> personelid
		{
			get
			{
				return this._personelid;
			}
			set
			{
				if ((this._personelid != value))
				{
					this.OnpersonelidChanging(value);
					this.SendPropertyChanging();
					this._personelid = value;
					this.SendPropertyChanged("personelid");
					this.OnpersonelidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personel_adi", DbType="NVarChar(50)")]
		public string personel_adi
		{
			get
			{
				return this._personel_adi;
			}
			set
			{
				if ((this._personel_adi != value))
				{
					this.Onpersonel_adiChanging(value);
					this.SendPropertyChanging();
					this._personel_adi = value;
					this.SendPropertyChanged("personel_adi");
					this.Onpersonel_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personel_sifre", DbType="NVarChar(50)")]
		public string personel_sifre
		{
			get
			{
				return this._personel_sifre;
			}
			set
			{
				if ((this._personel_sifre != value))
				{
					this.Onpersonel_sifreChanging(value);
					this.SendPropertyChanging();
					this._personel_sifre = value;
					this.SendPropertyChanged("personel_sifre");
					this.Onpersonel_sifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personel_no", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int personel_no
		{
			get
			{
				return this._personel_no;
			}
			set
			{
				if ((this._personel_no != value))
				{
					this.Onpersonel_noChanging(value);
					this.SendPropertyChanging();
					this._personel_no = value;
					this.SendPropertyChanged("personel_no");
					this.Onpersonel_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personel_ürünler", Storage="_ürünlers", ThisKey="personel_no", OtherKey="personel_no")]
		public EntitySet<ürünler> ürünlers
		{
			get
			{
				return this._ürünlers;
			}
			set
			{
				this._ürünlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ürünlers(ürünler entity)
		{
			this.SendPropertyChanging();
			entity.personel = this;
		}
		
		private void detach_ürünlers(ürünler entity)
		{
			this.SendPropertyChanging();
			entity.personel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Siparis")]
	public partial class Sipari
	{
		
		private System.Nullable<int> _siparisid;
		
		private System.Nullable<int> _siparis_no;
		
		private string _siparis_durumu;
		
		private System.Nullable<int> _ürün_serino;
		
		public Sipari()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisid", DbType="Int")]
		public System.Nullable<int> siparisid
		{
			get
			{
				return this._siparisid;
			}
			set
			{
				if ((this._siparisid != value))
				{
					this._siparisid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparis_no", DbType="Int")]
		public System.Nullable<int> siparis_no
		{
			get
			{
				return this._siparis_no;
			}
			set
			{
				if ((this._siparis_no != value))
				{
					this._siparis_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparis_durumu", DbType="NVarChar(50)")]
		public string siparis_durumu
		{
			get
			{
				return this._siparis_durumu;
			}
			set
			{
				if ((this._siparis_durumu != value))
				{
					this._siparis_durumu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ürün_serino", DbType="Int")]
		public System.Nullable<int> ürün_serino
		{
			get
			{
				return this._ürün_serino;
			}
			set
			{
				if ((this._ürün_serino != value))
				{
					this._ürün_serino = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ürünler")]
	public partial class ürünler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ürünid;
		
		private string _ürün_adi;
		
		private string _ürün_modeli;
		
		private int _ürün_serino;
		
		private System.Nullable<decimal> _ürün_adedi;
		
		private System.Nullable<System.DateTime> _ürün_tarihi;
		
		private System.Nullable<decimal> _fiyat;
		
		private System.Nullable<int> _personel_no;
		
		private EntityRef<kullanıcı> _kullanıcı;
		
		private EntityRef<personel> _personel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnürünidChanging(int value);
    partial void OnürünidChanged();
    partial void Onürün_adiChanging(string value);
    partial void Onürün_adiChanged();
    partial void Onürün_modeliChanging(string value);
    partial void Onürün_modeliChanged();
    partial void Onürün_serinoChanging(int value);
    partial void Onürün_serinoChanged();
    partial void Onürün_adediChanging(System.Nullable<decimal> value);
    partial void Onürün_adediChanged();
    partial void Onürün_tarihiChanging(System.Nullable<System.DateTime> value);
    partial void Onürün_tarihiChanged();
    partial void OnfiyatChanging(System.Nullable<decimal> value);
    partial void OnfiyatChanged();
    partial void Onpersonel_noChanging(System.Nullable<int> value);
    partial void Onpersonel_noChanged();
    #endregion
		
		public ürünler()
		{
			this._kullanıcı = default(EntityRef<kullanıcı>);
			this._personel = default(EntityRef<personel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ürünid", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ürünid
		{
			get
			{
				return this._ürünid;
			}
			set
			{
				if ((this._ürünid != value))
				{
					if (this._kullanıcı.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnürünidChanging(value);
					this.SendPropertyChanging();
					this._ürünid = value;
					this.SendPropertyChanged("ürünid");
					this.OnürünidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ürün_adi", DbType="NVarChar(50)")]
		public string ürün_adi
		{
			get
			{
				return this._ürün_adi;
			}
			set
			{
				if ((this._ürün_adi != value))
				{
					this.Onürün_adiChanging(value);
					this.SendPropertyChanging();
					this._ürün_adi = value;
					this.SendPropertyChanged("ürün_adi");
					this.Onürün_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ürün_modeli", DbType="NVarChar(50)")]
		public string ürün_modeli
		{
			get
			{
				return this._ürün_modeli;
			}
			set
			{
				if ((this._ürün_modeli != value))
				{
					this.Onürün_modeliChanging(value);
					this.SendPropertyChanging();
					this._ürün_modeli = value;
					this.SendPropertyChanged("ürün_modeli");
					this.Onürün_modeliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ürün_serino", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ürün_serino
		{
			get
			{
				return this._ürün_serino;
			}
			set
			{
				if ((this._ürün_serino != value))
				{
					this.Onürün_serinoChanging(value);
					this.SendPropertyChanging();
					this._ürün_serino = value;
					this.SendPropertyChanged("ürün_serino");
					this.Onürün_serinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ürün_adedi", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ürün_adedi
		{
			get
			{
				return this._ürün_adedi;
			}
			set
			{
				if ((this._ürün_adedi != value))
				{
					this.Onürün_adediChanging(value);
					this.SendPropertyChanging();
					this._ürün_adedi = value;
					this.SendPropertyChanged("ürün_adedi");
					this.Onürün_adediChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ürün_tarihi", DbType="Date")]
		public System.Nullable<System.DateTime> ürün_tarihi
		{
			get
			{
				return this._ürün_tarihi;
			}
			set
			{
				if ((this._ürün_tarihi != value))
				{
					this.Onürün_tarihiChanging(value);
					this.SendPropertyChanging();
					this._ürün_tarihi = value;
					this.SendPropertyChanged("ürün_tarihi");
					this.Onürün_tarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> fiyat
		{
			get
			{
				return this._fiyat;
			}
			set
			{
				if ((this._fiyat != value))
				{
					this.OnfiyatChanging(value);
					this.SendPropertyChanging();
					this._fiyat = value;
					this.SendPropertyChanged("fiyat");
					this.OnfiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personel_no", DbType="Int")]
		public System.Nullable<int> personel_no
		{
			get
			{
				return this._personel_no;
			}
			set
			{
				if ((this._personel_no != value))
				{
					if (this._personel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpersonel_noChanging(value);
					this.SendPropertyChanging();
					this._personel_no = value;
					this.SendPropertyChanged("personel_no");
					this.Onpersonel_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kullanıcı_ürünler", Storage="_kullanıcı", ThisKey="ürünid", OtherKey="kullanıcıid", IsForeignKey=true)]
		public kullanıcı kullanıcı
		{
			get
			{
				return this._kullanıcı.Entity;
			}
			set
			{
				kullanıcı previousValue = this._kullanıcı.Entity;
				if (((previousValue != value) 
							|| (this._kullanıcı.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kullanıcı.Entity = null;
						previousValue.ürünlers.Remove(this);
					}
					this._kullanıcı.Entity = value;
					if ((value != null))
					{
						value.ürünlers.Add(this);
						this._ürünid = value.kullanıcıid;
					}
					else
					{
						this._ürünid = default(int);
					}
					this.SendPropertyChanged("kullanıcı");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personel_ürünler", Storage="_personel", ThisKey="personel_no", OtherKey="personel_no", IsForeignKey=true)]
		public personel personel
		{
			get
			{
				return this._personel.Entity;
			}
			set
			{
				personel previousValue = this._personel.Entity;
				if (((previousValue != value) 
							|| (this._personel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._personel.Entity = null;
						previousValue.ürünlers.Remove(this);
					}
					this._personel.Entity = value;
					if ((value != null))
					{
						value.ürünlers.Add(this);
						this._personel_no = value.personel_no;
					}
					else
					{
						this._personel_no = default(Nullable<int>);
					}
					this.SendPropertyChanged("personel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
